# Generated by Django 4.2.4 on 2023-08-28 17:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.author', verbose_name='Post_Author'),
        ),
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 8, 28, 22, 29, 37, 317551), unique=True),
            preserve_default=False,
        ),
    ]
