# Generated by Django 3.2.6 on 2023-08-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_author_posts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
