# Generated by Django 3.2.6 on 2023-08-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
