# Generated by Django 3.2.6 on 2023-09-03 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230903_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.comment', verbose_name='Post_Comment'),
        ),
    ]
